### ISSUE TITLE
tf_ranking_libsvm example failes when group_size is 1

### ISSUE THREAD

**Issue by amir-rahnama** [tensorflow/ranking#233]
When I am running the tf_ranking_libsvm.py ( https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py) example with group size 1, I get the following error: 

```
Traceback (most recent call last):
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [272] vs. [900,136]
         [[{{node groupwise_dnn_v2/group_score/batch_normalization/batchnorm/mul_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf_ranking_example.py", line 502, in <module>
    tf.compat.v1.app.run()
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_ranking_example.py", line 493, in main
    train_and_eval()
  File "tf_ranking_example.py", line 487, in train_and_eval
    estimator.evaluate(input_fn=test_input_fn, hooks=[test_hook])
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 461, in evaluate
    return self._actual_eval(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 493, in _evaluate
    return self._evaluate_run(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1637, in _evaluate_run
    eval_results = evaluation._evaluate_once(  # pylint: disable=protected-access
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/training/evaluation.py", line 272, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 774, in run
    return self._sess.run(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1279, in run
    return self._sess.run(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1437, in run
    outputs = _WrappedSession.run(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [272] vs. [900,136]
         [[node groupwise_dnn_v2/group_score/batch_normalization/batchnorm/mul_1 (defined at tf_ranking_example.py:361) ]]

Errors may have originated from an input operation.
Input Source operations connected to node groupwise_dnn_v2/group_score/batch_normalization/batchnorm/mul_1:
 groupwise_dnn_v2/group_score/input_layer/concat (defined at tf_ranking_example.py:352)

Original stack trace for 'groupwise_dnn_v2/group_score/batch_normalization/batchnorm/mul_1':
  File "tf_ranking_example.py", line 502, in <module>
    tf.compat.v1.app.run()
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tf_ranking_example.py", line 493, in main
    train_and_eval()
  File "tf_ranking_example.py", line 487, in train_and_eval
    estimator.evaluate(input_fn=test_input_fn, hooks=[test_hook])
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 461, in evaluate
    return self._actual_eval(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 510, in _actual_eval
    return _evaluate()
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 492, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1528, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1563, in _call_model_fn_eval
    estimator_spec = self._call_model_fn(features, labels, ModeKeys.EVAL,
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/amirh/.local/lib/python3.8/site-packages/tensorflow_ranking/python/model.py", line 445, in _model_fn
    logits = ranking_model.compute_logits(features, labels, mode, params,
  File "/home/amirh/.local/lib/python3.8/site-packages/tensorflow_ranking/python/model.py", line 131, in compute_logits
    logits = self._compute_logits_impl(context_features, example_features,
  File "/home/amirh/.local/lib/python3.8/site-packages/tensorflow_ranking/python/model.py", line 383, in _compute_logits_impl
    scores = self._score_fn(large_batch_context_features,
  File "tf_ranking_example.py", line 361, in _score_fn
    cur_layer = tf.compat.v1.layers.batch_normalization(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/keras/legacy_tf_layers/normalization.py", line 336, in batch_normalization
    return layer.apply(inputs, training=training)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 1701, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/keras/legacy_tf_layers/base.py", line 547, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py", line 776, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 532, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 339, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/keras/legacy_tf_layers/normalization.py", line 172, in call
    return super(BatchNormalization, self).call(inputs, training=training)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/keras/layers/normalization.py", line 862, in call
    outputs = nn.batch_normalization(inputs, _broadcast(mean),
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/ops/nn_impl.py", line 1541, in batch_normalization
    return x * math_ops.cast(inv, x.dtype) + math_ops.cast(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1125, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 1457, in _mul_dispatch
    return multiply(x, y, name=name)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 509, in multiply
    return gen_math_ops.mul(x, y, name)
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6175, in mul
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 742, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3477, in _create_op_internal
    ret = Operation(
  File "/home/amirh/anaconda3/envs/tf_gpu/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1949, in __init__
    self._traceback = tf_stack.extract_stack()
```

What is causing the issue?

**Comment by xuanhuiwang** [comment]
This error seems to suggest that you may have group_size = 2 at some place:

Incompatible shapes: [272] vs. [900,136]

**Comment by amir-rahnama** [comment]
True, I had a hard coded value somewhere.

Doesn't the code work for different group-size? Why isn't the code working for group size more than one?
