### ISSUE TITLE
 ValueError: could not convert string to float

### ISSUE THREAD

**Issue by waldstein1983** [tensorflow/ranking#24]
Traceback (most recent call last):
  File "/home/Downloads/ranking/./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary.runfiles/org_tensorflow_ranking/tensorflow_ranking/examples/tf_ranking_libsvm.py", line 338, in <module>
    tf.app.run()
  File "/tmp/tfr/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/Downloads/ranking/./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary.runfiles/org_tensorflow_ranking/tensorflow_ranking/examples/tf_ranking_libsvm.py", line 329, in main
    train_and_eval()
  File "/home/Downloads/ranking/./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary.runfiles/org_tensorflow_ranking/tensorflow_ranking/examples/tf_ranking_libsvm.py", line 283, in train_and_eval
    FLAGS.list_size)
  File "/home/Downloads/ranking/./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary.runfiles/org_tensorflow_ranking/tensorflow_ranking/examples/tf_ranking_libsvm.py", line 144, in load_libsvm_data
    qid, features, label = _parse_line(line)
  File "/home/Downloads/ranking/./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary.runfiles/org_tensorflow_ranking/tensorflow_ranking/examples/tf_ranking_libsvm.py", line 126, in _parse_line
    features = {k: float(v) for (k, v) in kv_pairs}
  File "/home/Downloads/ranking/./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary.runfiles/org_tensorflow_ranking/tensorflow_ranking/examples/tf_ranking_libsvm.py", line 126, in <dictcomp>
    features = {k: float(v) for (k, v) in kv_pairs}
ValueError: could not convert string to float:

Does that mean no supporting for string feature?
Thanks

**Comment by waldstein1983** [comment]
I double confirmed that all feature values are numbers....

**Comment by kkonevets** [comment]
can you paste here several lines from file to see? Maybe there are blank lines?

**Comment by waldstein1983** [comment]
Here are some samples (the first column is the line number):
     15347 0 qid:348 1:2 2:0 3:33166 4:5259 5:30 6:2017 7:4265 8:0 9:0 10:5646 11:23 12:120.0 13:0 14:2725 15:0 16:909 17:2149 18:0
     15348 0 qid:349 1:1 2:0 3:33899 4:0 5:30 6:2088 7:2257 8:33022 9:0 10:0 11:24 12:120.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15349 0 qid:349 1:1 2:0 3:0 4:0 5:30 6:2339 7:167 8:0 9:0 10:0 11:0 12:140.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15350 0 qid:349 1:1 2:0 3:32768 4:0 5:30 6:0 7:46 8:0 9:0 10:0 11:0 12:120.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15351 0 qid:349 1:1 2:0 3:33346 4:0 5:30 6:0 7:235 8:0 9:0 10:0 11:0 12:160.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15352 0 qid:349 1:15 2:0 3:32996 4:4558 5:50 6:3997 7:667 8:33311 9:0 10:5940 11:15 12:100.0 13:0 14:5476 15:0 16:0 17:20000 18:0
     15353 0 qid:349 1:14 2:0 3:33705 4:3116 5:50 6:1065 7:1222 8:32915 9:0 10:5940 11:3 12:100.0 13:0 14:5400 15:0 16:0 17:20000 18:0
     15354 0 qid:349 1:1 2:0 3:34008 4:0 5:30 6:951 7:2430 8:0 9:0 10:0 11:12 12:140.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15355 0 qid:349 1:1 2:0 3:32725 4:0 5:50 6:0 7:120 8:0 9:0 10:0 11:7 12:100.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15356 0 qid:349 1:1 2:0 3:0 4:0 5:50 6:0 7:0 8:0 9:0 10:0 11:0 12:100.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15357 0 qid:349 1:1 2:0 3:33184 4:0 5:50 6:0 7:1178 8:0 9:0 10:0 11:0 12:100.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15358 0 qid:349 1:2 2:0 3:32969 4:3088 5:50 6:0 7:211 8:0 9:0 10:1188 11:1 12:100.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15359 1 qid:349 1:1 2:0 3:35302 4:0 5:30 6:1870 7:3325 8:0 9:0 10:0 11:11 12:140.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15360 0 qid:349 1:1 2:0 3:33223 4:0 5:30 6:1532 7:2271 8:0 9:0 10:0 11:2 12:140.0 13:0 14:0 15:0 16:0 17:20000 18:0
     15361 0 qid:349 1:0 2:0 3:0 4:4068 5:70 6:0 7:0 8:0 9:0 10:5940 11:0 12:100.0 13:0 14:5400 15:0 16:0 17:20000 18:0
     15362 1 qid:350 1:13 2:0 3:34793 4:5040 5:30 6:911 7:2673 8:33473 9:1 10:1016 11:24 12:120.0 13:0 14:1207 15:2 16:857 17:687 18:1
     15363 0 qid:350 1:9 2:0 3:33762 4:4326 5:30 6:2156 7:811 8:33132 9:1 10:5484 11:2 12:120.0 13:0 14:3537 15:0 16:1053 17:5860 18:1
     15364 0 qid:350 1:0 2:0 3:0 4:3236 5:50 6:0 7:12 8:0 9:1 10:1273 11:1 12:100.0 13:0 14:1922 15:0 16:956 17:2232 18:1

**Comment by kkonevets** [comment]
what is the first column? First column should be ranks

**Comment by waldstein1983** [comment]
First column is the LINE NUMBER in vim. It is not part of the data file

**Comment by kkonevets** [comment]
yeah, I am sorry, did not noticed. 
hm, this snippet looks good for me. Try to print contents of kv_pairs on error on line 126.
Something like 
```
try:
    features = {k: float(v) for (k, v) in kv_pairs}
except:
    print(features.values())
    raise Exception
```
