### ISSUE TITLE
Tensorflow Estimator no longer supported

### ISSUE THREAD

**Issue by chabazite** [tensorflow/ranking#362]
It appears the newest version of tensorflow no longer supports the estimator function, which is used in tensorflow-ranking. You probably already know this an have a fix for the next update, just wanted to call it out in case.

**Comment by pabx06** [comment]
same issue here . trying to make nixos package for tensorflow-ranking, fails at import check of `tensorflow_ranking`

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <lambda>
  File "/nix/store/nmqxyr00in2arwrq5qd1qipsanz1yrn5-python3-3.11.10/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/qnw76s433q5divmh07rsd386kjy38f8v-python3.11-tensorflow-ranking-0.5.3/lib/python3.11/site-packages/tensorflow_ranking/__init__.py", line 20, in <module>
    from tensorflow_ranking import extension as ext
  File "/nix/store/qnw76s433q5divmh07rsd386kjy38f8v-python3.11-tensorflow-ranking-0.5.3/lib/python3.11/site-packages/tensorflow_ranking/extension/__init__.py", line 21, in <module>
    from tensorflow_ranking.extension import pipeline
  File "/nix/store/qnw76s433q5divmh07rsd386kjy38f8v-python3.11-tensorflow-ranking-0.5.3/lib/python3.11/site-packages/tensorflow_ranking/extension/pipeline.py", line 24, in <module>
    from tensorflow import estimator as tf_estimator
ImportError: cannot import name 'estimator' from 'tensorflow' (/nix/store/f45c2147yfw7lz3cbrdnzx1182lfsgah-python3.11-tensorflow-2.18.0/lib/python3.11/site-packages/tensorflow/__init__.py)
```

**Comment by pabx06** [comment]
https://www.tensorflow.org/guide/migrate/migrating_estimator

**Comment by pabx06** [comment]
Missing tensorflow.estimator Dependency
The error ImportError: cannot import name 'estimator' from 'tensorflow' occurs because tensorflow-ranking 0.5.3 depends on the legacy tf.estimator API, which is not included in current TensorFlow 2.18.0 by default. Instead, tensorflow-estimator is now a standalone package : 

- https://github.com/tensorflow/tensorflow/issues/23163
- https://github.com/tensorflow/tensorflow/issues/32952
