### ISSUE TITLE
Pair-wise losses fail when providing dynamically sized logits

### ISSUE THREAD

**Issue by felixmaximilian** [tensorflow/ranking#38]
First, thanks much for all the work and also for sharing it. Highly appreciated!
When using some of the provided ranking losses like _softmax_loss or _pairwise_hinge_loss I run into problems with the shape.
The reason is, that my logits depend on a placeholder in my graph, that has a flexible shape.
`self.array = tf.placeholder(tf.string, [None, None], name='array')  # Batch_size x C`
In _softmax_loss function and several other loss functions you use the function `unstack(...)` which cannot work with variable shapes (see details discussed here: [Using tf.unpack() when first dimension of Variable is None](https://stackoverflow.com/questions/39446313/using-tf-unpack-when-first-dimension-of-variable-is-none))
The unstack command is used within the loss functions to determine the topn.
Help is much appreciated.

My trace
```Traceback (most recent call last):
/var/log/application.log aws_ec2_instance_id='X'     File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
/var/log/application.log aws_ec2_instance_id='X'       "__main__", mod_spec)
/var/log/application.log aws_ec2_instance_id='X'     File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
/var/log/application.log aws_ec2_instance_id='X'       exec(code, run_globals)
/var/log/application.log aws_ec2_instance_id='X'     File "/opt/workspace/1.55233553599e+12/XXX-307d542f0b148f74ebd68f9b94c2d0432ab21d9f/models/training/runner.py", line 50, in <module>
/var/log/application.log aws_ec2_instance_id='X'       trainer.run()
/var/log/application.log aws_ec2_instance_id='X'     File "/opt/workspace/1.55233553599e+12/XXX-307d542f0b148f74ebd68f9b94c2d0432ab21d9f/models/training/trainer.py", line 109, in run
 23:04:51.751 recolab-tuning /var/log/application.log aws_ec2_instance_id='X'       **self.model_params
/var/log/application.log aws_ec2_instance_id='X'     File "/opt/workspace/1.55233553599e+12/XXX-307d542f0b148f74ebd68f9b94c2d0432ab21d9f/models/models_common/model_factory.py", line 44, in create_model
/var/log/application.log aws_ec2_instance_id='X'       **kwargs
/var/log/application.log aws_ec2_instance_id='X'     File "/opt/workspace/1.55233553599e+12/XXX-307d542f0b148f74ebd68f9b94c2d0432ab21d9f/models/models_common/model/model.py", line 10, in __init__
/var/log/application.log aws_ec2_instance_id='X'       self.create(*args, **kwargs)
 23:04:51.751 recolab-tuning /var/log/application.log aws_ec2_instance_id='X'     File "/opt/workspace/1.55233553599e+12/XXX-307d542f0b148f74ebd68f9b94c2d0432ab21d9f/models/models/catalog/catalog_v1.py", line 202, in create
/var/log/application.log aws_ec2_instance_id='X'       unfiltered_cross_entropy_loss = tfr.losses._softmax_loss(target_array, self.logits)
/var/log/application.log aws_ec2_instance_id='X'     File "/usr/local/lib/python3.5/dist-packages/tensorflow_ranking/python/losses.py", line 759, in _softmax_loss
 /var/log/application.log aws_ec2_instance_id='X'       labels, logits, weights)
/var/log/application.log aws_ec2_instance_id='X'     File "/usr/local/lib/python3.5/dist-packages/tensorflow_ranking/python/losses.py", line 481, in _sort_and_normalize
/var/log/application.log aws_ec2_instance_id='X'       _, topn = array_ops.unstack(array_ops.shape(logits))
/var/log/application.log aws_ec2_instance_id='X'     File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1026, in unstack
/var/log/application.log aws_ec2_instance_id='X'       raise ValueError("Cannot infer num from shape %s" % value_shape)
/var/log/application.log aws_ec2_instance_id='X'   ValueError: Cannot infer num from shape (?,)```

**Comment by xuanhuiwang** [comment]
Can you try  `topn = array_ops.shape(logits)[1]` to see whether it solves your problem?

**Comment by felixmaximilian** [comment]
I can confirm that using array_ops.shape does not have the same issue as the variant in the code which uses unstack().
I was also able to temporarily fix the issue by giving a hint for the shape to the logits tensor:

`self.logits.set_shape(target_array.shape)`
for some reason, the target_array tensor shape can be inferred although being a placeholder with uninitialized shape:
`self.target_array = tf.placeholder(tf.int32, [None, None], name='targets')`

**Comment by xuanhuiwang** [comment]
We will use array index to replace unstack. closing this now.
