### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by miguelwon** [tensorflow/ranking#45]
Can I use the metrics available in a custom metric of Keras? I tried to code a custom metroc like this:

```
def nDCG(y_true, y_pred):
    return metrics.mnormalized_discounted_cumulative_gain(y_true,y_pred,topn = 3)
```

but I get the error:

`AttributeError: 'tuple' object has no attribute 'dtype'
`

**Comment by ramakumar1729** [comment]
I'm not sure I understand the issue completely. Can you share the complete code snippet, with the error message?

**Comment by miguelwon** [comment]
I want to use a custom metric in keras, like it is shown in the [documentation](https://keras.io/metrics/) example:


```
import keras.backend as K

def mean_pred(y_true, y_pred):
    return K.mean(y_pred)

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy', mean_pred])
```


where instead of  using `mean_pred` I want to calculate nDCG. This is the full error message I get:




```
WARNING:tensorflow:From /mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-03-26 09:03:45.696171: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-26 09:03:45.997838: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-03-26 09:03:45.998278: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x68fa610 executing computations on platform CUDA. Devices:
2019-03-26 09:03:45.998295: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 980, Compute Capability 5.2
2019-03-26 09:03:46.019003: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-03-26 09:03:46.019418: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x6bbd380 executing computations on platform Host. Devices:
2019-03-26 09:03:46.019432: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-03-26 09:03:46.019578: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 980 major: 5 minor: 2 memoryClockRate(GHz): 1.291
pciBusID: 0000:01:00.0
totalMemory: 3.95GiB freeMemory: 3.87GiB
2019-03-26 09:03:46.019591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-03-26 09:03:46.020255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-26 09:03:46.020264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-03-26 09:03:46.020269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-03-26 09:03:46.020366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3659 MB memory) -> physical GPU (device: 0, name: GeForce GTX 980, pci bus id: 0000:01:00.0, compute capability: 5.2)
WARNING:tensorflow:From /mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/tensorflow_ranking/python/metrics.py:188: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/tensorflow_ranking/python/metrics.py:152: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Traceback (most recent call last):
  File "hierarchical.py", line 258, in <module>
    loss_weights={'out_terms': 1., 'out_dom': 0.1, 'out_mts': 0.1},metrics=[nDCG])
  File "/mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/keras/engine/training.py", line 451, in compile
    handle_metrics(output_metrics)
  File "/mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/keras/engine/training.py", line 420, in handle_metrics
    mask=masks[i])
  File "/mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/keras/engine/training_utils.py", line 423, in weighted
    return K.mean(score_array)
  File "/mnt/sdb/data-mwon/eurovoc/env/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1396, in mean
    if x.dtype.base_dtype == tf.bool:
AttributeError: 'tuple' object has no attribute 'dtype'
```

**Comment by ramakumar1729** [comment]
Tensorflow Ranking currently uses `tf.metrics`, and is not compatible with `tf.keras.metrics` yet. I'll open a feature request for this.

**Comment by ramakumar1729** [comment]
Closing this for now. Please add any further comments on this to feature request #55.
