### ISSUE TITLE
feeding data too slow

### ISSUE THREAD

**Issue by supersush** [tensorflow/ranking#56]
Hi,i have a large training set.So i use libsvm_generator to construct my dataset.But the cpu usage is really low.Do you have any api or methods like "Parallelize Data Transformation" in tensorflow Data Input Pipeline Performance guide so i can feeding data in parallel?

**Comment by sbruch** [comment]
The libsvm input data pipeline is for demo purposes only. We recommend either using the SequenceExample format using data.parse_from_sequence_example(), or writing a custom input pipeline that makes sense for your data format and latency requirements.

**Comment by supersush** [comment]
Hi,i follow your advice to use data.parse_from_sequence_example(),but i got some errors.Please help me to find what's wrong with my code. @sbruch  
Another question is where  to add labels to SequenceExample?  Like this: feature_list {key: "label"}  ?
 
This is  my code:
`import tensorflow as tf
import tensorflow_ranking as tfr
from google.protobuf import text_format

SEQ_EXAMPLE_PROTO_1 = text_format.Parse(
    """
    context {
      feature {
        key: "query_length"
        value { int64_list { value: 3 } }
      }
    }
    feature_lists {
      feature_list {
        key: "unigrams"
        value {
          feature { bytes_list { value: "tensorflow" } }
          feature { bytes_list { value: ["learning", "to", "rank"] } }
        }
      }
      feature_list {
        key: "utility"
        value {
          feature { float_list { value: 0.0 } }
          feature { float_list { value: 1.0 } }
        }
      }
      feature_list {
        key: "feature1"
        value {
          feature { int64_list { value: 0 } }
          feature { int64_list { value: 1 } }
        }
      }
    }
    """, tf.train.SequenceExample())

CONTEXT_FEATURE_SPEC = {
    "query_length": tf.io.FixedLenFeature([1], tf.int64, default_value=[0])
}

EXAMPLE_FEATURE_SPEC = {
    "unigrams": tf.io.VarLenFeature(tf.string),
    "utility": tf.io.FixedLenFeature([1], tf.float32, default_value=[-1.]),
    "feature1": tf.io.FixedLenFeature([1], tf.int64, default_value=[0]),

}

if __name__ == "__main__":

    features = tfr.python.data.parse_from_sequence_example(
        tf.convert_to_tensor(value=[
            SEQ_EXAMPLE_PROTO_1.SerializeToString(),
        ]),
        2,
        example_feature_spec=EXAMPLE_FEATURE_SPEC)
    print(features)`

This is the error:
Traceback (most recent call last):
  File "/Users/usre/git_repo/order_refuse_predict/rerank_new/tf-ranking/sequence_example_test2.py", line 74, in <module>
    example_feature_spec=EXAMPLE_FEATURE_SPEC)
  File "/Users/usre/Library/Python/2.7/lib/python/site-packages/tensorflow_ranking/python/data.py", line 131, in parse_from_sequence_example
    tensor = control_flow_ops.cond(num_frames > list_size, slice_fn, pad_fn)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2108, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1941, in BuildCondBranch
    original_result = fn()
  File "/Users/usre/Library/Python/2.7/lib/python/site-packages/tensorflow_ranking/python/data.py", line 129, in pad_fn
    example_feature_spec[k].default_value[0]))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2297, in pad
    tensor, paddings, constant_values, name=name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5626, in pad_v2
    constant_values=constant_values, name=name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 547, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'constant_values' of 'PadV2' Op has type int32 that does not match type int64 of argument 'input'.

**Comment by xuanhuiwang** [comment]
In this code, `utility` is like `label`. `label` is expected to be float in tf-ranking.

For your error, you can change your `feature1` to type int32 and this should solve the problem. We are polish our data parsing and will release some better version soon.

**Comment by bendersky** [comment]
Closing this for now. Please let us know if your problem persists.

**Comment by supersush** [comment]
I change to int32 and get this error:

**Comment by supersush** [comment]
I change to int32 and get this error:
TypeError: Value passed to parameter 'feature_list_dense_types' has DataType int32 not in list of allowed values: float32, int64, string

Hope to see your new parsing relsase soon. @xuanhuiwang
