### ISSUE TITLE
export_savedmodel error

### ISSUE THREAD

**Issue by theoqian** [tensorflow/ranking#68]
I try to make model for tensorflow serving by:
```
feature_spec = tf.feature_column.make_parse_example_spec(feature_columns) 
export_input_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)
estimator.export_savedmodel('pairwise_serving_model', export_input_fn)
```
But get the following error:
```
Traceback (most recent call last):
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 521, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 521, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\util\compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x000001DD39FF80F0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Codes/ranking/model.py", line 167, in <module>
    train_pairwise()
  File "C:/Codes/ranking/model.py", line 162, in train_pairwise
    estimator.export_savedmodel('pairwise_serving_model', export_input_fn)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 663, in export_savedmodel
    mode=model_fn_lib.ModeKeys.PREDICT)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 716, in _export_saved_model_for_mode
    strip_default_attrs=strip_default_attrs)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 824, in _export_all_saved_models
    mode=model_fn_lib.ModeKeys.PREDICT)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 897, in _add_meta_graph_for_mode
    config=self.config)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_ranking\python\model.py", line 282, in _model_fn
    logits = _groupwise_dnn_v2(features, labels, mode, params, config)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow_ranking\python\model.py", line 246, in _groupwise_dnn_v2
    value = array_ops.gather_nd(value, indices)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3645, in gather_nd
    "GatherNd", params=params, indices=indices, name=name)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "C:\Users\theoq\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 525, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("ParseExample/ParseExample:0", shape=(?, 2), dtype=int64), values=Tensor("ParseExample/ParseExample:5", shape=(?,), dtype=int64), dense_shape=Tensor("ParseExample/ParseExample:10", shape=(2,), dtype=int64)). Consider casting elements to a supported type.
```

**Comment by theoqian** [comment]
I found the same error in tensorflow issues: https://github.com/tensorflow/tensorflow/issues/25980

**Comment by nsalerni** [comment]
Hi @theoqian. For tf_ranking_libsvm.py and tf_ranking_libsvm.ipynb it is sufficient to add the following to export the model in SavedModel format:

```
    # Export Model
    def example_feature_spec():
        """Returns the example feature columns."""
        feature_names = [
            "%d" % (i + 1) for i in range(0, FLAGS.num_features)
        ]
        return {
            name: tf.FixedLenFeature([1], tf.float32) for name in feature_names
        }

    feature_spec = example_feature_spec()
    serving_input_receiver_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)
    estimator.export_savedmodel('export', serving_input_receiver_fn)
```

It seems as though your feature_spec contains the wrong types. 

Hope this helps!

**Comment by theoqian** [comment]
> 
> 
> Hi @theoqian. For tf_ranking_libsvm.py and tf_ranking_libsvm.ipynb it is sufficient to add the following to export the model in SavedModel format:
> 
> ```
>     # Export Model
>     def example_feature_spec():
>         """Returns the example feature columns."""
>         feature_names = [
>             "%d" % (i + 1) for i in range(0, FLAGS.num_features)
>         ]
>         return {
>             name: tf.FixedLenFeature([1], tf.float32) for name in feature_names
>         }
> 
>     feature_spec = example_feature_spec()
>     serving_input_receiver_fn = tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)
>     estimator.export_savedmodel('export', serving_input_receiver_fn)
> ```
> 
> It seems as though your feature_spec contains the wrong types.
> 
> Hope this helps!

Thanks for you help. I trid to use the same feature_spec with premde estimator such as DNNClassifier and export savedmodel successfully. Have you trid the tf.feature_column.make_parse_example_spec function and did you get the same error as mine? Thanks.

**Comment by xuanhuiwang** [comment]
For feature_spec = tf.feature_column.make_parse_example_spec(feature_columns) , can you please check whether you can get the correct feature_spec after this call? Note that the arg for this call should not be a dict.

**Comment by nsalerni** [comment]
@theoqian I have not tried the tf.feature_column.make_parse_example_spec function.

**Comment by theoqian** [comment]
> 
> 
> For feature_spec = tf.feature_column.make_parse_example_spec(feature_columns) , can you please check whether you can get the correct feature_spec after this call? Note that the arg for this call should not be a dict.

I get the correct feature_spec. I use the same feature_spec in premade DNNClassifier and successfully export a savedmodel for serving. The arg 'feature_columns' which I use for this call is a list.

**Comment by theoqian** [comment]
I tried to use tf.feature_column.numeric_column only and export savedmodel successfully. But when I added tf.feature_column.indicator_column or tf.feature_column.embedding_column to feature_columns I got this error. I found that only numeric_column was used in tf_ranking_libsvm example. I think you can try to use indicator_column or embedding_column to reproduce the error. 
Thanks!

**Comment by xuanhuiwang** [comment]
@theoqian, thank you so much for debugging this. I am sorry that our example code missed one part for the demo purpose.

At [this place](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py#L312), we can have a `transform_fn` as an arg, such a function is meant to convert all features to dense Tensors. You can change it as

```
transform_fn=make_transform_fn(),
```

where `make_transform_fn` is defined as

```
def make_transform_fn():
  """Returns a transform_fn that converts features to dense Tensors."""

  def _transform_fn(features, mode):
    """Defines the transform fn."""
    example_name = next(six.iterkeys(example_feature_columns()))
    input_size = tf.shape(input=features[example_name])[1]
    context_features, example_features = tfr.feature.encode_listwise_features(
          features=features,
          input_size=input_size,
          context_feature_columns=None,
          example_feature_columns=example_feature_columns(),
          mode=mode,
          scope="transform_layer")

  return context_features, example_features

  return _transform_fn
```

**Comment by theoqian** [comment]
@xuanhuiwang Cool, excellent solution. Thanks!
